/********************************************************************************
** Form generated from reading UI file 'qvision.ui'
**
** Created by: Qt User Interface Compiler version 6.5.3
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_QVISION_H
#define UI_QVISION_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_QVision
{
public:
    QAction *actionOpen;
    QAction *actionSave;
    QAction *actionExit;
    QAction *actionRename_File;
    QAction *actionWriteToData;
    QAction *actionOutputImg_Data;
    QAction *actionResizeImgSize;
    QAction *actionOutputFile_Info;
    QAction *actionAbout;
    QAction *actionGray_Transform;
    QAction *actionLog_Transform;
    QAction *actionLinear_Transform;
    QAction *actionGamma_Transform;
    QAction *actionBox_Filter;
    QAction *actionMean_Filter;
    QAction *actionMedium_Filter;
    QAction *actionBilateral_Filter;
    QAction *actionGauss_Filter;
    QAction *actionDilation;
    QAction *actionErosion;
    QAction *actionSobel;
    QAction *actionCanny;
    QAction *actionScharr;
    QAction *actionRegion_Grow;
    QAction *actionFix_Threshold;
    QAction *actionShow_Outline;
    QAction *actionThreshold_Process;
    QAction *actionAdapt_Threshold;
    QAction *actionArea_Cover;
    QAction *actionArea_Fill;
    QAction *actionStatistic_Pixels;
    QAction *actionPerspective_Transform;
    QAction *actionCalculate_Distance;
    QAction *actionRotate_Scale;
    QAction *actionImage_Pyramid;
    QAction *actionDivide;
    QAction *actionOpen_2;
    QAction *actionClose_2;
    QAction *actionMultipy;
    QAction *actionLinear_Stretch;
    QAction *actionAdd;
    QAction *actionSubtraction;
    QAction *actionFourier;
    QAction *actionLaplacian;
    QAction *actionSURF;
    QAction *actionFlood_Fill;
    QAction *actionImage_Equal;
    QAction *actionTemplate_Match;
    QAction *actionFeature_Point_MAtch;
    QAction *actionUpgrade_TempMatch;
    QAction *actionLine;
    QAction *actionCircle;
    QAction *actionEllipse;
    QAction *actionTriangle;
    QAction *actionBallard;
    QAction *actionGuil;
    QAction *actionSpyder;
    QAction *actionSelf_Define_Model;
    QAction *actionLaunch;
    QAction *actionPick_Color;
    QAction *actionDetect_Face;
    QAction *actionRecongnize_Face;
    QAction *actionShi_Tomasi;
    QAction *actionHarris;
    QAction *actionFast;
    QAction *actionBrisk;
    QAction *actionMser;
    QAction *actionGFTT;
    QAction *actionTesseract_OCR;
    QAction *actionCapture_Line;
    QAction *actionCapture_Circle;
    QAction *actionCapture_Triangle;
    QAction *actionCapture_Ellpise;
    QAction *actionCapture_Character;
    QAction *actionVideo_Player;
    QAction *actionCapture_Square;
    QAction *actionFollow;
    QAction *actionDataBase;
    QAction *actionCSDN;
    QAction *actionJueJin;
    QAction *actionScreen_Cut;
    QAction *actionWakeUp_QQ;
    QAction *actionCapture_HumanEyes;
    QAction *actionCapture_HumanFace;
    QAction *actionTCP_IP;
    QAction *actionEraser;
    QAction *actionRectangle;
    QAction *actionLaunch_2;
    QWidget *centralwidget;
    QStatusBar *statusbar;
    QMenuBar *menubar;
    QMenu *menu;
    QMenu *menu_2;
    QMenu *menuGray_Image;
    QMenu *menuDecline_Noise;
    QMenu *menuShapes_Process;
    QMenu *menu_3;
    QMenu *menuDetect_Edges;
    QMenu *menu_4;
    QMenu *menu_5;
    QMenu *menuHough_Transform;
    QMenu *menuArbitary;
    QMenu *menuCorner_Detect;
    QMenu *menu_6;
    QMenu *menu_7;
    QMenu *menuDynamic_Capture;
    QMenu *menu_9;
    QMenu *menu_11;
    QMenu *menu_8;
    QMenu *menu_12;

    void setupUi(QMainWindow *QVision)
    {
        if (QVision->objectName().isEmpty())
            QVision->setObjectName("QVision");
        QVision->resize(1159, 621);
        actionOpen = new QAction(QVision);
        actionOpen->setObjectName("actionOpen");
        actionSave = new QAction(QVision);
        actionSave->setObjectName("actionSave");
        actionExit = new QAction(QVision);
        actionExit->setObjectName("actionExit");
        actionRename_File = new QAction(QVision);
        actionRename_File->setObjectName("actionRename_File");
        actionWriteToData = new QAction(QVision);
        actionWriteToData->setObjectName("actionWriteToData");
        actionOutputImg_Data = new QAction(QVision);
        actionOutputImg_Data->setObjectName("actionOutputImg_Data");
        actionResizeImgSize = new QAction(QVision);
        actionResizeImgSize->setObjectName("actionResizeImgSize");
        actionOutputFile_Info = new QAction(QVision);
        actionOutputFile_Info->setObjectName("actionOutputFile_Info");
        actionAbout = new QAction(QVision);
        actionAbout->setObjectName("actionAbout");
        actionGray_Transform = new QAction(QVision);
        actionGray_Transform->setObjectName("actionGray_Transform");
        actionLog_Transform = new QAction(QVision);
        actionLog_Transform->setObjectName("actionLog_Transform");
        actionLinear_Transform = new QAction(QVision);
        actionLinear_Transform->setObjectName("actionLinear_Transform");
        actionGamma_Transform = new QAction(QVision);
        actionGamma_Transform->setObjectName("actionGamma_Transform");
        actionBox_Filter = new QAction(QVision);
        actionBox_Filter->setObjectName("actionBox_Filter");
        actionMean_Filter = new QAction(QVision);
        actionMean_Filter->setObjectName("actionMean_Filter");
        actionMedium_Filter = new QAction(QVision);
        actionMedium_Filter->setObjectName("actionMedium_Filter");
        actionBilateral_Filter = new QAction(QVision);
        actionBilateral_Filter->setObjectName("actionBilateral_Filter");
        actionGauss_Filter = new QAction(QVision);
        actionGauss_Filter->setObjectName("actionGauss_Filter");
        actionDilation = new QAction(QVision);
        actionDilation->setObjectName("actionDilation");
        actionErosion = new QAction(QVision);
        actionErosion->setObjectName("actionErosion");
        actionSobel = new QAction(QVision);
        actionSobel->setObjectName("actionSobel");
        actionCanny = new QAction(QVision);
        actionCanny->setObjectName("actionCanny");
        actionScharr = new QAction(QVision);
        actionScharr->setObjectName("actionScharr");
        actionRegion_Grow = new QAction(QVision);
        actionRegion_Grow->setObjectName("actionRegion_Grow");
        actionFix_Threshold = new QAction(QVision);
        actionFix_Threshold->setObjectName("actionFix_Threshold");
        actionShow_Outline = new QAction(QVision);
        actionShow_Outline->setObjectName("actionShow_Outline");
        actionThreshold_Process = new QAction(QVision);
        actionThreshold_Process->setObjectName("actionThreshold_Process");
        actionAdapt_Threshold = new QAction(QVision);
        actionAdapt_Threshold->setObjectName("actionAdapt_Threshold");
        actionArea_Cover = new QAction(QVision);
        actionArea_Cover->setObjectName("actionArea_Cover");
        actionArea_Fill = new QAction(QVision);
        actionArea_Fill->setObjectName("actionArea_Fill");
        actionStatistic_Pixels = new QAction(QVision);
        actionStatistic_Pixels->setObjectName("actionStatistic_Pixels");
        actionPerspective_Transform = new QAction(QVision);
        actionPerspective_Transform->setObjectName("actionPerspective_Transform");
        actionCalculate_Distance = new QAction(QVision);
        actionCalculate_Distance->setObjectName("actionCalculate_Distance");
        actionRotate_Scale = new QAction(QVision);
        actionRotate_Scale->setObjectName("actionRotate_Scale");
        actionImage_Pyramid = new QAction(QVision);
        actionImage_Pyramid->setObjectName("actionImage_Pyramid");
        actionDivide = new QAction(QVision);
        actionDivide->setObjectName("actionDivide");
        actionOpen_2 = new QAction(QVision);
        actionOpen_2->setObjectName("actionOpen_2");
        actionClose_2 = new QAction(QVision);
        actionClose_2->setObjectName("actionClose_2");
        actionMultipy = new QAction(QVision);
        actionMultipy->setObjectName("actionMultipy");
        actionLinear_Stretch = new QAction(QVision);
        actionLinear_Stretch->setObjectName("actionLinear_Stretch");
        actionAdd = new QAction(QVision);
        actionAdd->setObjectName("actionAdd");
        actionSubtraction = new QAction(QVision);
        actionSubtraction->setObjectName("actionSubtraction");
        actionFourier = new QAction(QVision);
        actionFourier->setObjectName("actionFourier");
        actionLaplacian = new QAction(QVision);
        actionLaplacian->setObjectName("actionLaplacian");
        actionSURF = new QAction(QVision);
        actionSURF->setObjectName("actionSURF");
        actionFlood_Fill = new QAction(QVision);
        actionFlood_Fill->setObjectName("actionFlood_Fill");
        actionImage_Equal = new QAction(QVision);
        actionImage_Equal->setObjectName("actionImage_Equal");
        actionTemplate_Match = new QAction(QVision);
        actionTemplate_Match->setObjectName("actionTemplate_Match");
        actionFeature_Point_MAtch = new QAction(QVision);
        actionFeature_Point_MAtch->setObjectName("actionFeature_Point_MAtch");
        actionUpgrade_TempMatch = new QAction(QVision);
        actionUpgrade_TempMatch->setObjectName("actionUpgrade_TempMatch");
        actionLine = new QAction(QVision);
        actionLine->setObjectName("actionLine");
        actionCircle = new QAction(QVision);
        actionCircle->setObjectName("actionCircle");
        actionEllipse = new QAction(QVision);
        actionEllipse->setObjectName("actionEllipse");
        actionTriangle = new QAction(QVision);
        actionTriangle->setObjectName("actionTriangle");
        actionBallard = new QAction(QVision);
        actionBallard->setObjectName("actionBallard");
        actionGuil = new QAction(QVision);
        actionGuil->setObjectName("actionGuil");
        actionSpyder = new QAction(QVision);
        actionSpyder->setObjectName("actionSpyder");
        actionSelf_Define_Model = new QAction(QVision);
        actionSelf_Define_Model->setObjectName("actionSelf_Define_Model");
        actionLaunch = new QAction(QVision);
        actionLaunch->setObjectName("actionLaunch");
        actionPick_Color = new QAction(QVision);
        actionPick_Color->setObjectName("actionPick_Color");
        actionDetect_Face = new QAction(QVision);
        actionDetect_Face->setObjectName("actionDetect_Face");
        actionRecongnize_Face = new QAction(QVision);
        actionRecongnize_Face->setObjectName("actionRecongnize_Face");
        actionShi_Tomasi = new QAction(QVision);
        actionShi_Tomasi->setObjectName("actionShi_Tomasi");
        actionHarris = new QAction(QVision);
        actionHarris->setObjectName("actionHarris");
        actionFast = new QAction(QVision);
        actionFast->setObjectName("actionFast");
        actionBrisk = new QAction(QVision);
        actionBrisk->setObjectName("actionBrisk");
        actionMser = new QAction(QVision);
        actionMser->setObjectName("actionMser");
        actionGFTT = new QAction(QVision);
        actionGFTT->setObjectName("actionGFTT");
        actionTesseract_OCR = new QAction(QVision);
        actionTesseract_OCR->setObjectName("actionTesseract_OCR");
        actionCapture_Line = new QAction(QVision);
        actionCapture_Line->setObjectName("actionCapture_Line");
        actionCapture_Circle = new QAction(QVision);
        actionCapture_Circle->setObjectName("actionCapture_Circle");
        actionCapture_Triangle = new QAction(QVision);
        actionCapture_Triangle->setObjectName("actionCapture_Triangle");
        actionCapture_Ellpise = new QAction(QVision);
        actionCapture_Ellpise->setObjectName("actionCapture_Ellpise");
        actionCapture_Character = new QAction(QVision);
        actionCapture_Character->setObjectName("actionCapture_Character");
        actionVideo_Player = new QAction(QVision);
        actionVideo_Player->setObjectName("actionVideo_Player");
        actionCapture_Square = new QAction(QVision);
        actionCapture_Square->setObjectName("actionCapture_Square");
        actionFollow = new QAction(QVision);
        actionFollow->setObjectName("actionFollow");
        actionDataBase = new QAction(QVision);
        actionDataBase->setObjectName("actionDataBase");
        actionCSDN = new QAction(QVision);
        actionCSDN->setObjectName("actionCSDN");
        actionJueJin = new QAction(QVision);
        actionJueJin->setObjectName("actionJueJin");
        actionScreen_Cut = new QAction(QVision);
        actionScreen_Cut->setObjectName("actionScreen_Cut");
        actionWakeUp_QQ = new QAction(QVision);
        actionWakeUp_QQ->setObjectName("actionWakeUp_QQ");
        actionCapture_HumanEyes = new QAction(QVision);
        actionCapture_HumanEyes->setObjectName("actionCapture_HumanEyes");
        actionCapture_HumanFace = new QAction(QVision);
        actionCapture_HumanFace->setObjectName("actionCapture_HumanFace");
        actionTCP_IP = new QAction(QVision);
        actionTCP_IP->setObjectName("actionTCP_IP");
        actionEraser = new QAction(QVision);
        actionEraser->setObjectName("actionEraser");
        actionRectangle = new QAction(QVision);
        actionRectangle->setObjectName("actionRectangle");
        actionLaunch_2 = new QAction(QVision);
        actionLaunch_2->setObjectName("actionLaunch_2");
        centralwidget = new QWidget(QVision);
        centralwidget->setObjectName("centralwidget");
        QVision->setCentralWidget(centralwidget);
        statusbar = new QStatusBar(QVision);
        statusbar->setObjectName("statusbar");
        QVision->setStatusBar(statusbar);
        menubar = new QMenuBar(QVision);
        menubar->setObjectName("menubar");
        menubar->setGeometry(QRect(0, 0, 1159, 20));
        menu = new QMenu(menubar);
        menu->setObjectName("menu");
        menu_2 = new QMenu(menubar);
        menu_2->setObjectName("menu_2");
        menuGray_Image = new QMenu(menu_2);
        menuGray_Image->setObjectName("menuGray_Image");
        menuDecline_Noise = new QMenu(menu_2);
        menuDecline_Noise->setObjectName("menuDecline_Noise");
        menuShapes_Process = new QMenu(menu_2);
        menuShapes_Process->setObjectName("menuShapes_Process");
        menu_3 = new QMenu(menubar);
        menu_3->setObjectName("menu_3");
        menuDetect_Edges = new QMenu(menu_3);
        menuDetect_Edges->setObjectName("menuDetect_Edges");
        menu_4 = new QMenu(menubar);
        menu_4->setObjectName("menu_4");
        menu_5 = new QMenu(menubar);
        menu_5->setObjectName("menu_5");
        menuHough_Transform = new QMenu(menu_5);
        menuHough_Transform->setObjectName("menuHough_Transform");
        menuArbitary = new QMenu(menuHough_Transform);
        menuArbitary->setObjectName("menuArbitary");
        menuCorner_Detect = new QMenu(menu_5);
        menuCorner_Detect->setObjectName("menuCorner_Detect");
        menu_6 = new QMenu(menubar);
        menu_6->setObjectName("menu_6");
        menu_7 = new QMenu(menubar);
        menu_7->setObjectName("menu_7");
        menuDynamic_Capture = new QMenu(menu_7);
        menuDynamic_Capture->setObjectName("menuDynamic_Capture");
        menu_9 = new QMenu(menubar);
        menu_9->setObjectName("menu_9");
        menu_11 = new QMenu(menubar);
        menu_11->setObjectName("menu_11");
        menu_8 = new QMenu(menubar);
        menu_8->setObjectName("menu_8");
        menu_12 = new QMenu(menubar);
        menu_12->setObjectName("menu_12");
        QVision->setMenuBar(menubar);

        menubar->addAction(menu->menuAction());
        menubar->addAction(menu_2->menuAction());
        menubar->addAction(menu_3->menuAction());
        menubar->addAction(menu_4->menuAction());
        menubar->addAction(menu_5->menuAction());
        menubar->addAction(menu_6->menuAction());
        menubar->addAction(menu_7->menuAction());
        menubar->addAction(menu_9->menuAction());
        menubar->addAction(menu_8->menuAction());
        menubar->addAction(menu_12->menuAction());
        menubar->addAction(menu_11->menuAction());
        menu->addAction(actionOpen);
        menu->addSeparator();
        menu->addAction(actionSave);
        menu->addAction(actionExit);
        menu_2->addAction(menuGray_Image->menuAction());
        menu_2->addAction(menuDecline_Noise->menuAction());
        menu_2->addAction(menuShapes_Process->menuAction());
        menuGray_Image->addAction(actionGray_Transform);
        menuGray_Image->addAction(actionLog_Transform);
        menuGray_Image->addAction(actionLinear_Transform);
        menuGray_Image->addAction(actionGamma_Transform);
        menuDecline_Noise->addAction(actionBox_Filter);
        menuDecline_Noise->addAction(actionMean_Filter);
        menuDecline_Noise->addAction(actionMedium_Filter);
        menuDecline_Noise->addAction(actionBilateral_Filter);
        menuDecline_Noise->addAction(actionGauss_Filter);
        menuShapes_Process->addAction(actionDilation);
        menuShapes_Process->addAction(actionErosion);
        menu_3->addAction(menuDetect_Edges->menuAction());
        menu_3->addAction(actionRegion_Grow);
        menu_3->addAction(actionFix_Threshold);
        menu_3->addAction(actionShow_Outline);
        menu_3->addAction(actionThreshold_Process);
        menu_3->addAction(actionAdapt_Threshold);
        menu_3->addAction(actionArea_Cover);
        menu_3->addAction(actionArea_Fill);
        menu_3->addAction(actionStatistic_Pixels);
        menu_3->addAction(actionPerspective_Transform);
        menu_3->addAction(actionCalculate_Distance);
        menu_3->addAction(actionRotate_Scale);
        menu_3->addAction(actionImage_Pyramid);
        menu_3->addAction(actionPick_Color);
        menu_3->addAction(actionScreen_Cut);
        menu_3->addAction(actionWakeUp_QQ);
        menu_3->addAction(actionEraser);
        menuDetect_Edges->addAction(actionSobel);
        menuDetect_Edges->addAction(actionCanny);
        menuDetect_Edges->addAction(actionScharr);
        menu_4->addAction(actionDivide);
        menu_4->addAction(actionOpen_2);
        menu_4->addAction(actionClose_2);
        menu_4->addAction(actionMultipy);
        menu_4->addAction(actionLinear_Stretch);
        menu_4->addAction(actionAdd);
        menu_4->addAction(actionSubtraction);
        menu_4->addAction(actionFourier);
        menu_4->addAction(actionLaplacian);
        menu_5->addAction(actionSURF);
        menu_5->addAction(actionFlood_Fill);
        menu_5->addAction(actionImage_Equal);
        menu_5->addAction(menuHough_Transform->menuAction());
        menu_5->addAction(menuCorner_Detect->menuAction());
        menu_5->addAction(actionTemplate_Match);
        menu_5->addAction(actionFeature_Point_MAtch);
        menu_5->addAction(actionUpgrade_TempMatch);
        menuHough_Transform->addAction(actionLine);
        menuHough_Transform->addAction(actionCircle);
        menuHough_Transform->addAction(actionEllipse);
        menuHough_Transform->addAction(actionTriangle);
        menuHough_Transform->addAction(menuArbitary->menuAction());
        menuHough_Transform->addAction(actionRectangle);
        menuArbitary->addAction(actionBallard);
        menuArbitary->addAction(actionGuil);
        menuCorner_Detect->addAction(actionShi_Tomasi);
        menuCorner_Detect->addAction(actionHarris);
        menuCorner_Detect->addAction(actionFast);
        menuCorner_Detect->addAction(actionBrisk);
        menuCorner_Detect->addAction(actionMser);
        menuCorner_Detect->addAction(actionGFTT);
        menu_6->addAction(actionRename_File);
        menu_6->addAction(actionWriteToData);
        menu_6->addAction(actionOutputImg_Data);
        menu_6->addAction(actionResizeImgSize);
        menu_6->addAction(actionOutputFile_Info);
        menu_7->addAction(actionSelf_Define_Model);
        menu_7->addAction(actionRecongnize_Face);
        menu_7->addAction(actionTesseract_OCR);
        menu_7->addAction(menuDynamic_Capture->menuAction());
        menuDynamic_Capture->addAction(actionCapture_Line);
        menuDynamic_Capture->addAction(actionCapture_Circle);
        menuDynamic_Capture->addAction(actionCapture_Triangle);
        menuDynamic_Capture->addAction(actionCapture_Ellpise);
        menuDynamic_Capture->addAction(actionCapture_Character);
        menuDynamic_Capture->addAction(actionCapture_Square);
        menuDynamic_Capture->addAction(actionCapture_HumanEyes);
        menuDynamic_Capture->addAction(actionCapture_HumanFace);
        menu_9->addAction(actionSpyder);
        menu_9->addAction(actionTCP_IP);
        menu_11->addAction(actionFollow);
        menu_11->addAction(actionCSDN);
        menu_11->addAction(actionJueJin);
        menu_8->addAction(actionVideo_Player);
        menu_12->addAction(actionLaunch_2);

        retranslateUi(QVision);

        QMetaObject::connectSlotsByName(QVision);
    } // setupUi

    void retranslateUi(QMainWindow *QVision)
    {
        QVision->setWindowTitle(QCoreApplication::translate("QVision", "QVision", nullptr));
        actionOpen->setText(QCoreApplication::translate("QVision", "Open", nullptr));
        actionSave->setText(QCoreApplication::translate("QVision", "Save", nullptr));
        actionExit->setText(QCoreApplication::translate("QVision", "Exit", nullptr));
        actionRename_File->setText(QCoreApplication::translate("QVision", "Rename File", nullptr));
        actionWriteToData->setText(QCoreApplication::translate("QVision", "WriteToData", nullptr));
        actionOutputImg_Data->setText(QCoreApplication::translate("QVision", "Output ImgData", nullptr));
        actionResizeImgSize->setText(QCoreApplication::translate("QVision", "Resize ImgSize", nullptr));
        actionOutputFile_Info->setText(QCoreApplication::translate("QVision", "Output File Info", nullptr));
        actionAbout->setText(QCoreApplication::translate("QVision", "About", nullptr));
        actionGray_Transform->setText(QCoreApplication::translate("QVision", "Gray Transform", nullptr));
        actionLog_Transform->setText(QCoreApplication::translate("QVision", "Log Transform", nullptr));
        actionLinear_Transform->setText(QCoreApplication::translate("QVision", "Linear Transform", nullptr));
        actionGamma_Transform->setText(QCoreApplication::translate("QVision", "Gamma Transform", nullptr));
        actionBox_Filter->setText(QCoreApplication::translate("QVision", "Box Filter", nullptr));
        actionMean_Filter->setText(QCoreApplication::translate("QVision", "Mean Filter", nullptr));
        actionMedium_Filter->setText(QCoreApplication::translate("QVision", "Medium Filter", nullptr));
        actionBilateral_Filter->setText(QCoreApplication::translate("QVision", "Bilateral Filter", nullptr));
        actionGauss_Filter->setText(QCoreApplication::translate("QVision", "Gauss Filter", nullptr));
        actionDilation->setText(QCoreApplication::translate("QVision", "Dilation", nullptr));
        actionErosion->setText(QCoreApplication::translate("QVision", "Erosion", nullptr));
        actionSobel->setText(QCoreApplication::translate("QVision", "Sobel", nullptr));
        actionCanny->setText(QCoreApplication::translate("QVision", "Canny", nullptr));
        actionScharr->setText(QCoreApplication::translate("QVision", "Scharr", nullptr));
        actionRegion_Grow->setText(QCoreApplication::translate("QVision", "Region Grow", nullptr));
        actionFix_Threshold->setText(QCoreApplication::translate("QVision", "Fix Threshold", nullptr));
        actionShow_Outline->setText(QCoreApplication::translate("QVision", "Show Outline", nullptr));
        actionThreshold_Process->setText(QCoreApplication::translate("QVision", "Threshold Process", nullptr));
        actionAdapt_Threshold->setText(QCoreApplication::translate("QVision", "Adapt Threshold", nullptr));
        actionArea_Cover->setText(QCoreApplication::translate("QVision", "Area Cover", nullptr));
        actionArea_Fill->setText(QCoreApplication::translate("QVision", "Area Fill", nullptr));
        actionStatistic_Pixels->setText(QCoreApplication::translate("QVision", "Statistic Pixels", nullptr));
        actionPerspective_Transform->setText(QCoreApplication::translate("QVision", "Perspective Transform", nullptr));
        actionCalculate_Distance->setText(QCoreApplication::translate("QVision", "Calculate Distance", nullptr));
        actionRotate_Scale->setText(QCoreApplication::translate("QVision", "Rotate Scale", nullptr));
        actionImage_Pyramid->setText(QCoreApplication::translate("QVision", "Image Pyramid", nullptr));
        actionDivide->setText(QCoreApplication::translate("QVision", "Divide", nullptr));
        actionOpen_2->setText(QCoreApplication::translate("QVision", "Open ", nullptr));
        actionClose_2->setText(QCoreApplication::translate("QVision", "Close", nullptr));
        actionMultipy->setText(QCoreApplication::translate("QVision", "Multipy", nullptr));
        actionLinear_Stretch->setText(QCoreApplication::translate("QVision", "Linear Stretch", nullptr));
        actionAdd->setText(QCoreApplication::translate("QVision", "Add", nullptr));
        actionSubtraction->setText(QCoreApplication::translate("QVision", "Subtraction", nullptr));
        actionFourier->setText(QCoreApplication::translate("QVision", "Fourier", nullptr));
        actionLaplacian->setText(QCoreApplication::translate("QVision", "Laplacian", nullptr));
        actionSURF->setText(QCoreApplication::translate("QVision", "SURF", nullptr));
        actionFlood_Fill->setText(QCoreApplication::translate("QVision", "Flood Fill", nullptr));
        actionImage_Equal->setText(QCoreApplication::translate("QVision", "Image Equal", nullptr));
        actionTemplate_Match->setText(QCoreApplication::translate("QVision", "Template Match", nullptr));
        actionFeature_Point_MAtch->setText(QCoreApplication::translate("QVision", "Feature Point Match", nullptr));
        actionUpgrade_TempMatch->setText(QCoreApplication::translate("QVision", "Upgrade TempMatch", nullptr));
        actionLine->setText(QCoreApplication::translate("QVision", "Line", nullptr));
        actionCircle->setText(QCoreApplication::translate("QVision", "Circle", nullptr));
        actionEllipse->setText(QCoreApplication::translate("QVision", "Ellipse", nullptr));
        actionTriangle->setText(QCoreApplication::translate("QVision", "Triangle", nullptr));
        actionBallard->setText(QCoreApplication::translate("QVision", "Ballard", nullptr));
        actionGuil->setText(QCoreApplication::translate("QVision", "Guil", nullptr));
        actionSpyder->setText(QCoreApplication::translate("QVision", "Spyder", nullptr));
        actionSelf_Define_Model->setText(QCoreApplication::translate("QVision", "Customize Model", nullptr));
        actionLaunch->setText(QCoreApplication::translate("QVision", "Launch", nullptr));
        actionPick_Color->setText(QCoreApplication::translate("QVision", "Pick Color", nullptr));
        actionDetect_Face->setText(QCoreApplication::translate("QVision", "Detect Face", nullptr));
        actionRecongnize_Face->setText(QCoreApplication::translate("QVision", "Recongnize Face", nullptr));
        actionShi_Tomasi->setText(QCoreApplication::translate("QVision", "Shi Tomasi", nullptr));
        actionHarris->setText(QCoreApplication::translate("QVision", "Harris", nullptr));
        actionFast->setText(QCoreApplication::translate("QVision", "Fast", nullptr));
        actionBrisk->setText(QCoreApplication::translate("QVision", "Brisk", nullptr));
        actionMser->setText(QCoreApplication::translate("QVision", "Mser", nullptr));
        actionGFTT->setText(QCoreApplication::translate("QVision", "GFTT", nullptr));
        actionTesseract_OCR->setText(QCoreApplication::translate("QVision", "Tesseract OCR", nullptr));
        actionCapture_Line->setText(QCoreApplication::translate("QVision", "Capture Line", nullptr));
        actionCapture_Circle->setText(QCoreApplication::translate("QVision", "Capture Circle", nullptr));
        actionCapture_Triangle->setText(QCoreApplication::translate("QVision", "Capture Triangle", nullptr));
        actionCapture_Ellpise->setText(QCoreApplication::translate("QVision", "Capture Ellpise", nullptr));
        actionCapture_Character->setText(QCoreApplication::translate("QVision", "Capture Character", nullptr));
        actionVideo_Player->setText(QCoreApplication::translate("QVision", "Video Player", nullptr));
        actionCapture_Square->setText(QCoreApplication::translate("QVision", "Capture Square", nullptr));
        actionFollow->setText(QCoreApplication::translate("QVision", "Github", nullptr));
        actionDataBase->setText(QCoreApplication::translate("QVision", "DataBase", nullptr));
        actionCSDN->setText(QCoreApplication::translate("QVision", "CSDN", nullptr));
        actionJueJin->setText(QCoreApplication::translate("QVision", "JueJin", nullptr));
        actionScreen_Cut->setText(QCoreApplication::translate("QVision", "Screen Cut", nullptr));
        actionWakeUp_QQ->setText(QCoreApplication::translate("QVision", "WakeUp QQ", nullptr));
        actionCapture_HumanEyes->setText(QCoreApplication::translate("QVision", "Capture HumanEyes", nullptr));
        actionCapture_HumanFace->setText(QCoreApplication::translate("QVision", "Capture HumanFace", nullptr));
        actionTCP_IP->setText(QCoreApplication::translate("QVision", "TCP IP", nullptr));
        actionEraser->setText(QCoreApplication::translate("QVision", "Eraser", nullptr));
        actionRectangle->setText(QCoreApplication::translate("QVision", "Rectangle", nullptr));
        actionLaunch_2->setText(QCoreApplication::translate("QVision", "Launch", nullptr));
        menu->setTitle(QCoreApplication::translate("QVision", "\346\226\207\344\273\266", nullptr));
        menu_2->setTitle(QCoreApplication::translate("QVision", "\351\242\204\345\244\204\347\220\206", nullptr));
        menuGray_Image->setTitle(QCoreApplication::translate("QVision", "Transform", nullptr));
        menuDecline_Noise->setTitle(QCoreApplication::translate("QVision", "Decline Noise", nullptr));
        menuShapes_Process->setTitle(QCoreApplication::translate("QVision", "Shapes Process", nullptr));
        menu_3->setTitle(QCoreApplication::translate("QVision", "\345\267\245\345\205\267", nullptr));
        menuDetect_Edges->setTitle(QCoreApplication::translate("QVision", "Detect Edges", nullptr));
        menu_4->setTitle(QCoreApplication::translate("QVision", "\350\277\220\347\256\227", nullptr));
        menu_5->setTitle(QCoreApplication::translate("QVision", "\347\256\227\346\263\225", nullptr));
        menuHough_Transform->setTitle(QCoreApplication::translate("QVision", "Hough Transform", nullptr));
        menuArbitary->setTitle(QCoreApplication::translate("QVision", "Arbitary", nullptr));
        menuCorner_Detect->setTitle(QCoreApplication::translate("QVision", "Corner Detect", nullptr));
        menu_6->setTitle(QCoreApplication::translate("QVision", "\346\211\271\345\244\204\347\220\206", nullptr));
        menu_7->setTitle(QCoreApplication::translate("QVision", "\346\250\241\345\236\213", nullptr));
        menuDynamic_Capture->setTitle(QCoreApplication::translate("QVision", "Dynamic Capture", nullptr));
        menu_9->setTitle(QCoreApplication::translate("QVision", "\347\275\221\347\273\234", nullptr));
        menu_11->setTitle(QCoreApplication::translate("QVision", "\345\205\263\344\272\216", nullptr));
        menu_8->setTitle(QCoreApplication::translate("QVision", "\345\252\222\344\275\223", nullptr));
        menu_12->setTitle(QCoreApplication::translate("QVision", "\346\225\260\346\215\256\345\272\223", nullptr));
    } // retranslateUi

};

namespace Ui {
    class QVision: public Ui_QVision {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_QVISION_H
