#ifndef DIALOG_H
#define DIALOG_H
#include "GuilDlg.h"
#include "CannyDlg.h"
#include "RenameDlg.h"
#include "ResizeDlg.h"
#include "BallardDlg.h"
#include "AreaFillDlg.h"
#include "RotScaleDlg.h"
#include "NetSpyderDlg.h"
#include "CalcuDistDlg.h"
#include "ThresholdDlg.h"
#include "WriteDataDlg.h"
#include "charrecogdlg.h"
#include "FixThresholdDlg.h"
#include "TemplateMatchDlg.h"
#include "StatisticPixelDlg.h"
#include "UpgradeTempMatchDlg.h"
#endif // DIALOG_H
